version: '3.3'
services:
  db:
    image: mariadb
    env_file:
      - ./.env
    volumes:
      - 'db_data:/var/lib/mysql'
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
  wordpress:
    depends_on:
      - db
    image: 'wordpress:latest'
    env_file:
      - ./.env
    volumes:
      - './html:/var/www/html'
      - './plugins/password-protected/:/var/www/html/wp-content/plugins/password-protected'
      - './uploads.ini:/usr/local/etc/php/conf.d/uploads.ini'
    ports:
      - '80:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: '${WORDPRESS_DB_HOST}'
      WORDPRESS_DB_USER: '${WORDPRESS_DB_USER}'
      WORDPRESS_DB_PASSWORD: '${WORDPRESS_DB_PASSWORD}'
      WORDPRESS_DB_NAME: '${WORDPRESS_DB_NAME}'
volumes:
  db_data: {}

